name: deploy

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install nodejs
      - run: sudo npm install --global citation-js
      - run: cmake -S . -B build
      - run: cmake --build build --target install
      - run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "GitHub Actions"
          git push
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
